### PR TITLE
Allows to set a callable for the `set` config option

### PR DESCRIPTION
**Pull request by HavokInspiration**
I found myself in a situation where I needed to do a bit of logic to set the value.
This gives the ability to use a callable as the `set` config option.
It takes only one argument : the current value of the field.

### CODE REVIEW

**Comment by segy** [comment]
Hello. Nice idea. As I think of it now, I would prefer to change it to use the whole entity as a callable parameter. What do you say. Would you prefer to create PR for this or should I change it this way?

**Comment by HavokInspiration** [comment]
That's a good idea.
I can make the change to this PR tonight or tomorrow.

**Comment by segy** [comment]
Fine. Thank you very much.

**Comment by HavokInspiration** [comment]
I updated the PR. The callable now receives the full Entity being cloned as parameter.

**Pull request merged**
